class NoBaseUrlError(Exception): ...


class TokenRefreshError(Exception): ...


class InsufficientQueryArgsSet(Exception): ...


class NoFiltersSetException(Exception): ...


class NoDivisionSetException(Exception): ...


class DailyLimitExceededException(Exception): ...
